[package]
name = "objq"
version = "0.1.2"
authors = ["Satoshi Amemiya"]

[dependencies]
serde = "*"
serde_macros = "*"
serde_json = "*"
docopt = "*"
docopt_macros = "*"
rustc-serialize = "*"
peg = "*"
yaml-rust = "*"
rmp-serde = "*"
